on:
  push:
    branches:
      - main

env:
  STATIS_PREFIX: main

jobs:
  satis:
    runs-on: ubuntu-latest
    container: ghcr.io/composer/satis:latest
    env:
      STATIS_HOMEPAGE: https://tao-ce.github.io/registry-composer/${{ env.STATIS_PREFIX }}
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
        fetch-depth: 1
        set-safe-directory: '*'

    - uses: actions/checkout@v6
      with:
        path: public
        ref: github-pages
        fetch-depth: 1
        set-safe-directory: '*'

    - run:
        /satis/bin/satis --ansi -vvv -n build satis.json public/${{ env.STATIS_PREFIX }}
      

    - working-directory: public
      run: |
        git config user.name "Github Action satis update"
        git config user.email "<>"
        git add .
        git commit -m 'ci: satis update'
