on:
  push:
    branches:
      - main

env:
  SATIS_PREFIX: main

jobs:
  satis:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

    - uses: shivammathur/setup-php@v2
      env:
        COMPOSER_ALLOW_PLUGINS: composer/satis

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v5
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - uses: actions/checkout@v6
      with:
        submodules: recursive
        fetch-depth: 1
        set-safe-directory: '*'

    - uses: actions/checkout@v6
      with:
        path: public
        ref: github-pages
        fetch-depth: 1
        set-safe-directory: '*'

    - run: |
        export SATIS_HOMEPAGE=https://tao-ce.github.io/registry-composer/${{ env.SATIS_PREFIX }}

        composer create-project composer/satis:dev-main
        php satis/bin/satis --ansi -vvv -n build satis.json public/${{ env.SATIS_PREFIX }}
      

    - working-directory: public
      run: |
        git config user.name "Github Action satis update"
        git config user.email "<>"
        git add .
        git commit -m 'ci: satis update'
        git push

